services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Assignment2
      - JWT_SECRET=ushna
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    build:
      context: ./database  
      dockerfile: Dockerfile
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data:
